# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mxboard_pb2 as mxboard__pb2


class MXNetServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.createSymbol = channel.unary_unary(
        '/MXNetService/createSymbol',
        request_serializer=mxboard__pb2.SymbolParameter.SerializeToString,
        response_deserializer=mxboard__pb2.SymbolCreateState.FromString,
        )
    self.startTask = channel.unary_unary(
        '/MXNetService/startTask',
        request_serializer=mxboard__pb2.TaskParameter.SerializeToString,
        response_deserializer=mxboard__pb2.TaskState.FromString,
        )
    self.stopTask = channel.unary_unary(
        '/MXNetService/stopTask',
        request_serializer=mxboard__pb2.TaskId.SerializeToString,
        response_deserializer=mxboard__pb2.TaskState.FromString,
        )


class MXNetServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def createSymbol(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def startTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def stopTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MXNetServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'createSymbol': grpc.unary_unary_rpc_method_handler(
          servicer.createSymbol,
          request_deserializer=mxboard__pb2.SymbolParameter.FromString,
          response_serializer=mxboard__pb2.SymbolCreateState.SerializeToString,
      ),
      'startTask': grpc.unary_unary_rpc_method_handler(
          servicer.startTask,
          request_deserializer=mxboard__pb2.TaskParameter.FromString,
          response_serializer=mxboard__pb2.TaskState.SerializeToString,
      ),
      'stopTask': grpc.unary_unary_rpc_method_handler(
          servicer.stopTask,
          request_deserializer=mxboard__pb2.TaskId.FromString,
          response_serializer=mxboard__pb2.TaskState.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'MXNetService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
