# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mxboard.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mxboard.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rmxboard.proto\"N\n\x0fSymbolParameter\x12\x11\n\tsymbol_id\x18\x01 \x02(\t\x12\x13\n\x0bsymbol_name\x18\x02 \x02(\t\x12\x13\n\x0bsymbol_desc\x18\x03 \x02(\t\"]\n\x11SymbolCreateState\x12\x11\n\tsymbol_id\x18\x01 \x02(\t\x12\x15\n\nstate_code\x18\x02 \x02(\x05:\x01\x30\x12\x1e\n\nstate_desc\x18\x03 \x02(\t:\nSUCCESSFUL\"7\n\rTaskParameter\x12\x13\n\x02id\x18\x01 \x02(\x0b\x32\x07.TaskId\x12\x11\n\ttask_desc\x18\x02 \x02(\t\"\x19\n\x06TaskId\x12\x0f\n\x07task_id\x18\x01 \x02(\t\"R\n\tTaskState\x12\x0f\n\x07task_id\x18\x01 \x02(\t\x12\x15\n\nstate_code\x18\x02 \x02(\x05:\x01\x30\x12\x1d\n\nstate_desc\x18\x03 \x02(\t:\tOK_TO_RUN2\x94\x01\n\x0cMXNetService\x12\x36\n\x0c\x63reateSymbol\x12\x10.SymbolParameter\x1a\x12.SymbolCreateState\"\x00\x12)\n\tstartTask\x12\x0e.TaskParameter\x1a\n.TaskState\"\x00\x12!\n\x08stopTask\x12\x07.TaskId\x1a\n.TaskState\"\x00')
)




_SYMBOLPARAMETER = _descriptor.Descriptor(
  name='SymbolParameter',
  full_name='SymbolParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol_id', full_name='SymbolParameter.symbol_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_name', full_name='SymbolParameter.symbol_name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='symbol_desc', full_name='SymbolParameter.symbol_desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=95,
)


_SYMBOLCREATESTATE = _descriptor.Descriptor(
  name='SymbolCreateState',
  full_name='SymbolCreateState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='symbol_id', full_name='SymbolCreateState.symbol_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_code', full_name='SymbolCreateState.state_code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_desc', full_name='SymbolCreateState.state_desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("SUCCESSFUL").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=190,
)


_TASKPARAMETER = _descriptor.Descriptor(
  name='TaskParameter',
  full_name='TaskParameter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='TaskParameter.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_desc', full_name='TaskParameter.task_desc', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=247,
)


_TASKID = _descriptor.Descriptor(
  name='TaskId',
  full_name='TaskId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='TaskId.task_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=274,
)


_TASKSTATE = _descriptor.Descriptor(
  name='TaskState',
  full_name='TaskState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='TaskState.task_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_code', full_name='TaskState.state_code', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_desc', full_name='TaskState.state_desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("OK_TO_RUN").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=358,
)

_TASKPARAMETER.fields_by_name['id'].message_type = _TASKID
DESCRIPTOR.message_types_by_name['SymbolParameter'] = _SYMBOLPARAMETER
DESCRIPTOR.message_types_by_name['SymbolCreateState'] = _SYMBOLCREATESTATE
DESCRIPTOR.message_types_by_name['TaskParameter'] = _TASKPARAMETER
DESCRIPTOR.message_types_by_name['TaskId'] = _TASKID
DESCRIPTOR.message_types_by_name['TaskState'] = _TASKSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SymbolParameter = _reflection.GeneratedProtocolMessageType('SymbolParameter', (_message.Message,), dict(
  DESCRIPTOR = _SYMBOLPARAMETER,
  __module__ = 'mxboard_pb2'
  # @@protoc_insertion_point(class_scope:SymbolParameter)
  ))
_sym_db.RegisterMessage(SymbolParameter)

SymbolCreateState = _reflection.GeneratedProtocolMessageType('SymbolCreateState', (_message.Message,), dict(
  DESCRIPTOR = _SYMBOLCREATESTATE,
  __module__ = 'mxboard_pb2'
  # @@protoc_insertion_point(class_scope:SymbolCreateState)
  ))
_sym_db.RegisterMessage(SymbolCreateState)

TaskParameter = _reflection.GeneratedProtocolMessageType('TaskParameter', (_message.Message,), dict(
  DESCRIPTOR = _TASKPARAMETER,
  __module__ = 'mxboard_pb2'
  # @@protoc_insertion_point(class_scope:TaskParameter)
  ))
_sym_db.RegisterMessage(TaskParameter)

TaskId = _reflection.GeneratedProtocolMessageType('TaskId', (_message.Message,), dict(
  DESCRIPTOR = _TASKID,
  __module__ = 'mxboard_pb2'
  # @@protoc_insertion_point(class_scope:TaskId)
  ))
_sym_db.RegisterMessage(TaskId)

TaskState = _reflection.GeneratedProtocolMessageType('TaskState', (_message.Message,), dict(
  DESCRIPTOR = _TASKSTATE,
  __module__ = 'mxboard_pb2'
  # @@protoc_insertion_point(class_scope:TaskState)
  ))
_sym_db.RegisterMessage(TaskState)



_MXNETSERVICE = _descriptor.ServiceDescriptor(
  name='MXNetService',
  full_name='MXNetService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=361,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='createSymbol',
    full_name='MXNetService.createSymbol',
    index=0,
    containing_service=None,
    input_type=_SYMBOLPARAMETER,
    output_type=_SYMBOLCREATESTATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startTask',
    full_name='MXNetService.startTask',
    index=1,
    containing_service=None,
    input_type=_TASKPARAMETER,
    output_type=_TASKSTATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stopTask',
    full_name='MXNetService.stopTask',
    index=2,
    containing_service=None,
    input_type=_TASKID,
    output_type=_TASKSTATE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MXNETSERVICE)

DESCRIPTOR.services_by_name['MXNetService'] = _MXNETSERVICE

# @@protoc_insertion_point(module_scope)
